In [3]:
import numpy as np
x=np.linspace(0,10,100)
y= np.cos(x)
z= np.sin(x)

In [5]:
# x
y

array([ 1.        ,  0.99490282,  0.97966323,  0.95443659,  0.91948007,
        0.87515004,  0.8218984 ,  0.76026803,  0.69088721,  0.61446323,
        0.53177518,  0.44366602,  0.35103397,  0.25482335,  0.15601496,
        0.0556161 , -0.04534973, -0.14585325, -0.24486989, -0.34139023,
       -0.43443032, -0.52304166, -0.60632092, -0.68341913, -0.75355031,
       -0.81599952, -0.87013012, -0.91539031, -0.95131866, -0.97754893,
       -0.9938137 , -0.99994717, -0.9958868 , -0.981674  , -0.95745366,
       -0.92347268, -0.88007748, -0.82771044, -0.76690542, -0.69828229,
       -0.6225406 , -0.54045251, -0.45285485, -0.36064061, -0.26474988,
       -0.16616018, -0.06587659,  0.03507857,  0.13567613,  0.23489055,
        0.33171042,  0.4251487 ,  0.51425287,  0.59811455,  0.67587883,
        0.74675295,  0.8100144 ,  0.86501827,  0.91120382,  0.94810022,
        0.97533134,  0.99261957,  0.99978867,  0.99676556,  0.98358105,
        0.96036956,  0.9273677 ,  0.88491192,  0.83343502,  0.77

In [6]:
y

array([ 1.        ,  0.99490282,  0.97966323,  0.95443659,  0.91948007,
        0.87515004,  0.8218984 ,  0.76026803,  0.69088721,  0.61446323,
        0.53177518,  0.44366602,  0.35103397,  0.25482335,  0.15601496,
        0.0556161 , -0.04534973, -0.14585325, -0.24486989, -0.34139023,
       -0.43443032, -0.52304166, -0.60632092, -0.68341913, -0.75355031,
       -0.81599952, -0.87013012, -0.91539031, -0.95131866, -0.97754893,
       -0.9938137 , -0.99994717, -0.9958868 , -0.981674  , -0.95745366,
       -0.92347268, -0.88007748, -0.82771044, -0.76690542, -0.69828229,
       -0.6225406 , -0.54045251, -0.45285485, -0.36064061, -0.26474988,
       -0.16616018, -0.06587659,  0.03507857,  0.13567613,  0.23489055,
        0.33171042,  0.4251487 ,  0.51425287,  0.59811455,  0.67587883,
        0.74675295,  0.8100144 ,  0.86501827,  0.91120382,  0.94810022,
        0.97533134,  0.99261957,  0.99978867,  0.99676556,  0.98358105,
        0.96036956,  0.9273677 ,  0.88491192,  0.83343502,  0.77

In [9]:
data =2* np.random.random((10,10))

In [10]:
data

array([[1.53129738],
       [0.03675885],
       [0.32132831],
       [0.09670585],
       [1.81394414],
       [0.26238338],
       [1.64738853],
       [1.88768867],
       [0.61397181],
       [0.5438922 ]])

In [11]:
y ,x = np.mgrid[-3:3:100j, -3:3:100j]

In [12]:
U = -1 - x-y**2 + y 

In [14]:
U

array([[-10.        , -10.06060606, -10.12121212, ..., -15.87878788,
        -15.93939394, -16.        ],
       [ -9.57943067,  -9.64003673,  -9.70064279, ..., -15.45821855,
        -15.51882461, -15.57943067],
       [ -9.16620753,  -9.22681359,  -9.28741965, ..., -15.04499541,
        -15.10560147, -15.16620753],
       ...,
       [ -3.40863177,  -3.46923783,  -3.52984389, ...,  -9.28741965,
         -9.34802571,  -9.40863177],
       [ -3.70064279,  -3.76124885,  -3.82185491, ...,  -9.57943067,
         -9.64003673,  -9.70064279],
       [ -4.        ,  -4.06060606,  -4.12121212, ...,  -9.87878788,
         -9.93939394, -10.        ]])

In [15]:
V = 1 + x-y**2

In [18]:
from  matplotlib.cbook import  get_sample_data

# img = np.load(get_sample_data('axes_grid/bivarate_normal.npy'))

In [ ]:
# img

In [19]:
# create plot
import matplotlib.pyplot as plt 

In [20]:
fig = plt.figure()

<Figure size 640x480 with 0 Axes>

In [21]:
fig

<Figure size 640x480 with 0 Axes>

In [23]:
fig2 = plt.figure(figsize=plt.figaspect(2.0))

<Figure size 400x800 with 0 Axes>

In [27]:
# fig.add_axes()
# ax1 = fig.add_subplot(221)
# ax2= fid.add_subplot(212)
# fig3,axes = plt.subplots(nrows=2,ncols=2) 
# fig4= , axes2 = plt.subplots(ncols=3)


#### 